### ISSUE TITLE
Do not run Composer as root/super user!

### ISSUE THREAD

**Issue by viniciuslk** [hjar/bitbucket-to-aws#1]

**Comment by hjar** [comment]
True, seeing that message on the pipeline's output is a valid concern. In this case however it'll only run in Bitbucket's temporary Docker container. I'll explain the process a bit:

1. A commit is made to master.
2. Bitbucket Pipelines starts a Docker container and pulls the code.
3. `bitbucket-pipelines-common.sh` is executed to set everything up. This includes populating the `vendor` directory with `composer install`, as root.
4. `phpunit` tests are run.
5. `bitbucket-pipelines-codedeploy.sh` packages the entire app directory in a .zip and lets CodeDeploy handle the deployment.
6. Bitbucket Pipelines stops the Docker container.

In this process `composer` is never run on the live instances, and it's very well sandboxed when it's run on Bitbucket's server. I hope this explanation helps.
